# Generated by Django 4.1 on 2022-09-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_watchlist_delete_mywatchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='watched',
            field=models.BooleanField(),
        ),
    ]
